# Generated by Django 3.1.3 on 2020-11-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201106_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='last',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='edad',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
