# Generated by Django 3.1.3 on 2020-11-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_apellidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mascotas',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
